// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantTelegramUserDao is internal type for wrapping internal DAO implements.
type internalMerchantTelegramUserDao = *internal.MerchantTelegramUserDao

// merchantTelegramUserDao is the data access object for table merchant_telegram_user.
// You can define custom methods on it to extend its functionality as you wish.
type merchantTelegramUserDao struct {
	internalMerchantTelegramUserDao
}

var (
	// MerchantTelegramUser is globally public accessible object for table merchant_telegram_user operations.
	MerchantTelegramUser = merchantTelegramUserDao{
		internal.NewMerchantTelegramUserDao(),
	}
)

// Fill with you ideas below.
