// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantScenarioExecutionDao is internal type for wrapping internal DAO implements.
type internalMerchantScenarioExecutionDao = *internal.MerchantScenarioExecutionDao

// merchantScenarioExecutionDao is the data access object for table merchant_scenario_execution.
// You can define custom methods on it to extend its functionality as you wish.
type merchantScenarioExecutionDao struct {
	internalMerchantScenarioExecutionDao
}

var (
	// MerchantScenarioExecution is globally public accessible object for table merchant_scenario_execution operations.
	MerchantScenarioExecution = merchantScenarioExecutionDao{
		internal.NewMerchantScenarioExecutionDao(),
	}
)

// Fill with you ideas below.
