// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantScenarioDelayedTaskDao is internal type for wrapping internal DAO implements.
type internalMerchantScenarioDelayedTaskDao = *internal.MerchantScenarioDelayedTaskDao

// merchantScenarioDelayedTaskDao is the data access object for table merchant_scenario_delayed_task.
// You can define custom methods on it to extend its functionality as you wish.
type merchantScenarioDelayedTaskDao struct {
	internalMerchantScenarioDelayedTaskDao
}

var (
	// MerchantScenarioDelayedTask is globally public accessible object for table merchant_scenario_delayed_task operations.
	MerchantScenarioDelayedTask = merchantScenarioDelayedTaskDao{
		internal.NewMerchantScenarioDelayedTaskDao(),
	}
)

// Fill with you ideas below.
