// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantScenarioDao is internal type for wrapping internal DAO implements.
type internalMerchantScenarioDao = *internal.MerchantScenarioDao

// merchantScenarioDao is the data access object for table merchant_scenario.
// You can define custom methods on it to extend its functionality as you wish.
type merchantScenarioDao struct {
	internalMerchantScenarioDao
}

var (
	// MerchantScenario is globally public accessible object for table merchant_scenario operations.
	MerchantScenario = merchantScenarioDao{
		internal.NewMerchantScenarioDao(),
	}
)

// Fill with you ideas below.
